{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "!django-admin startproject Tinash"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " Volume in drive C is OS\n",
      " Volume Serial Number is 8601-7E58\n",
      "\n",
      " Directory of c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\n",
      "\n",
      "2025-03-26  02:13 PM    <DIR>          .\n",
      "2025-03-23  11:56 AM    <DIR>          ..\n",
      "2025-03-23  11:41 AM                 0 __init__.py\n",
      "2025-03-23  11:56 AM    <DIR>          __pycache__\n",
      "2025-03-23  11:41 AM                66 admin.py\n",
      "2025-03-24  08:35 AM             3,062 alx_capstone.ipynb\n",
      "2025-03-23  11:41 AM               144 apps.py\n",
      "2025-03-23  11:56 AM    <DIR>          migrations\n",
      "2025-03-23  11:49 AM             2,289 models.py\n",
      "2025-03-23  11:41 AM                63 tests.py\n",
      "2025-03-23  11:41 AM                66 views.py\n",
      "               7 File(s)          5,690 bytes\n",
      "               4 Dir(s)   6,726,848,512 bytes free\n"
     ]
    }
   ],
   "source": [
    "ls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\n"
     ]
    }
   ],
   "source": [
    "%cd ."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\n"
     ]
    }
   ],
   "source": [
    "cd c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#!python manage.py startapp api"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No changes detected\n",
      "Operations to perform:\n",
      "  Apply all migrations: admin, api, auth, contenttypes, sessions\n",
      "Running migrations:\n",
      "  No migrations to apply.\n"
     ]
    }
   ],
   "source": [
    "!python manage.py makemigrations\n",
    "!python manage.py migrate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "^C\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 26, 2025 - 19:40:35\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 26, 2025 - 22:45:59\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 11:23:43\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 11:34:41\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 11:53:35\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 11:56:36\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 11:57:24\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 12:00:06\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\serializers.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 126, in inner_run\n",
      "    autoreload.raise_last_exception()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 87, in raise_last_exception\n",
      "    raise _exception[1]\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\__init__.py\", line 394, in execute\n",
      "    autoreload.check_errors(django.setup)()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\__init__.py\", line 24, in setup\n",
      "    apps.populate(settings.INSTALLED_APPS)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\registry.py\", line 91, in populate\n",
      "    app_config = AppConfig.create(entry)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\config.py\", line 193, in create\n",
      "    import_module(entry)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1324, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'Users'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 126, in inner_run\n",
      "    autoreload.raise_last_exception()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 87, in raise_last_exception\n",
      "    raise _exception[1]\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\__init__.py\", line 394, in execute\n",
      "    autoreload.check_errors(django.setup)()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\__init__.py\", line 24, in setup\n",
      "    apps.populate(settings.INSTALLED_APPS)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\registry.py\", line 91, in populate\n",
      "    app_config = AppConfig.create(entry)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\config.py\", line 193, in create\n",
      "    import_module(entry)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1324, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'Users'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 126, in inner_run\n",
      "    autoreload.raise_last_exception()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 87, in raise_last_exception\n",
      "    raise _exception[1]\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\__init__.py\", line 394, in execute\n",
      "    autoreload.check_errors(django.setup)()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\__init__.py\", line 24, in setup\n",
      "    apps.populate(settings.INSTALLED_APPS)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\registry.py\", line 91, in populate\n",
      "    app_config = AppConfig.create(entry)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\config.py\", line 193, in create\n",
      "    import_module(entry)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1324, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'users'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 126, in inner_run\n",
      "    autoreload.raise_last_exception()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 87, in raise_last_exception\n",
      "    raise _exception[1]\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\__init__.py\", line 394, in execute\n",
      "    autoreload.check_errors(django.setup)()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\__init__.py\", line 24, in setup\n",
      "    apps.populate(settings.INSTALLED_APPS)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\registry.py\", line 91, in populate\n",
      "    app_config = AppConfig.create(entry)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\config.py\", line 193, in create\n",
      "    import_module(entry)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1324, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'users'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Internal Server Error: /api/users/\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n",
      "    response = get_response(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n",
      "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n",
      "    return view_func(request, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\viewsets.py\", line 124, in view\n",
      "    return self.dispatch(request, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n",
      "    response = self.handle_exception(exc)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n",
      "    self.raise_uncaught_exception(exc)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n",
      "    raise exc\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n",
      "    response = handler(request, *args, **kwargs)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\mixins.py\", line 46, in list\n",
      "    return Response(serializer.data)\n",
      "                    ^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\serializers.py\", line 795, in data\n",
      "    ret = super().data\n",
      "          ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\serializers.py\", line 249, in data\n",
      "    self._data = self.to_representation(self.instance)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\serializers.py\", line 714, in to_representation\n",
      "    self.child.to_representation(item) for item in iterable\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\serializers.py\", line 523, in to_representation\n",
      "    for field in fields:\n",
      "                 ^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\serializers.py\", line 384, in _readable_fields\n",
      "    for field in self.fields.values():\n",
      "                 ^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\serializers.py\", line 372, in fields\n",
      "    for key, value in self.get_fields().items():\n",
      "                      ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\serializers.py\", line 1103, in get_fields\n",
      "    field_class, field_kwargs = self.build_field(\n",
      "                                ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\serializers.py\", line 1249, in build_field\n",
      "    return self.build_unknown_field(field_name, model_class)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\serializers.py\", line 1367, in build_unknown_field\n",
      "    raise ImproperlyConfigured(\n",
      "django.core.exceptions.ImproperlyConfigured: Field name `is_seller` is not valid for model `User` in `api.serializers.UserSerializer`.\n",
      "[27/Mar/2025 11:24:29] \"GET /api/users/ HTTP/1.1\" 500 150140\n",
      "[27/Mar/2025 11:24:53] \"GET /api/orders/ HTTP/1.1\" 200 14424\n",
      "[27/Mar/2025 11:24:55] \"GET /api/orders/ HTTP/1.1\" 200 14424\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\serializers.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 5, in <module>\n",
      "    from permissions import IsSeller, IsBuyer\n",
      "ModuleNotFoundError: No module named 'permissions'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 5, in <module>\n",
      "    from permissions import IsSeller, IsBuyer\n",
      "ModuleNotFoundError: No module named 'permissions'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 5, in <module>\n",
      "    from permissions import IsSeller, IsBuyer\n",
      "ModuleNotFoundError: No module named 'permissions'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 5, in <module>\n",
      "    from permissions import IsSeller, IsBuyer\n",
      "ModuleNotFoundError: No module named 'permissions'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 13, in <module>\n",
      "    class ProductViewSet(viewsets.ModelViewSet):\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 17, in ProductViewSet\n",
      "    filter_backends = [DjangoFilterBackend, filters.SearchFilter]\n",
      "                                            ^^^^^^^\n",
      "NameError: name 'filters' is not defined. Did you mean: 'filter'?\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 136, in check_custom_error_handlers\n",
      "    handler = resolver.resolve_error_handler(status_code)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 732, in resolve_error_handler\n",
      "    callback = getattr(self.urlconf_module, \"handler%s\" % view_type, None)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 13, in <module>\n",
      "    class ProductViewSet(viewsets.ModelViewSet):\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 17, in ProductViewSet\n",
      "    filter_backends = [DjangoFilterBackend, filter.SearchFilter]\n",
      "                                            ^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: type object 'filter' has no attribute 'SearchFilter'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 13, in <module>\n",
      "    class ProductViewSet(viewsets.ModelViewSet):\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 17, in ProductViewSet\n",
      "    filter_backends = [DjangoFilterBackend, filters.SearchFilter]\n",
      "                                            ^^^^^^^\n",
      "NameError: name 'filters' is not defined. Did you mean: 'filter'?\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "[27/Mar/2025 11:54:45] \"GET /api/products HTTP/1.1\" 301 0\n",
      "Internal Server Error: /api/products/\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\views.py\", line 497, in dispatch\n",
      "    self.initial(request, *args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\views.py\", line 415, in initial\n",
      "    self.check_permissions(request)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\views.py\", line 333, in check_permissions\n",
      "    self.permission_denied(\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\views.py\", line 174, in permission_denied\n",
      "    raise exceptions.NotAuthenticated()\n",
      "rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\settings.py\", line 179, in import_from_string\n",
      "    return import_string(val)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\module_loading.py\", line 30, in import_string\n",
      "    return cached_import(module_path, class_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\module_loading.py\", line 15, in cached_import\n",
      "    module = import_module(module_path)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1310, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1324, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'users'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n",
      "    response = get_response(request)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n",
      "    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n",
      "    return view_func(request, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\viewsets.py\", line 124, in view\n",
      "    return self.dispatch(request, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n",
      "    response = self.handle_exception(exc)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\views.py\", line 463, in handle_exception\n",
      "    exception_handler = self.get_exception_handler()\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\views.py\", line 298, in get_exception_handler\n",
      "    return self.settings.EXCEPTION_HANDLER\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\settings.py\", line 227, in __getattr__\n",
      "    val = perform_import(val, attr)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\settings.py\", line 168, in perform_import\n",
      "    return import_from_string(val, setting_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\settings.py\", line 182, in import_from_string\n",
      "    raise ImportError(msg)\n",
      "ImportError: Could not import 'users.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'users'.\n",
      "[27/Mar/2025 11:54:45] \"GET /api/products/ HTTP/1.1\" 500 147466\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n"
     ]
    }
   ],
   "source": [
    "!python manage.py runserver\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "^C\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 26, 2025 - 19:39:06\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 26, 2025 - 19:40:15\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 26, 2025 - 22:45:54\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 11:23:44\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 11:34:39\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 11:53:41\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 11:56:33\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 11:57:29\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "March 27, 2025 - 12:00:11\n",
      "Django version 5.1.6, using settings 'Tinash.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CTRL-BREAK.\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 563, in check\n",
      "    raise SystemCheckError(msg)\n",
      "django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:\n",
      "\n",
      "ERRORS:\n",
      "?: (urls.E004) Your URL pattern \"path('users/', UserViewSet.as_view(), name='user-list'),\\n    path('products/', ProductViewSet.as_view(), name='product-list'),\\n    path('orders/', OrderViewSet.as_view(), name='order-list'),\\n\" is invalid. Ensure that urlpatterns is a list of path() and/or re_path() instances.\n",
      "\tHINT: Try removing the string 'path('users/', UserViewSet.as_view(), name='user-list'),\n",
      "    path('products/', ProductViewSet.as_view(), name='product-list'),\n",
      "    path('orders/', OrderViewSet.as_view(), name='order-list'),\n",
      "'. The list of urlpatterns should not have a prefix string as the first element.\n",
      "\n",
      "System check identified 1 issue (0 silenced).\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 563, in check\n",
      "    raise SystemCheckError(msg)\n",
      "django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:\n",
      "\n",
      "ERRORS:\n",
      "?: (urls.E004) Your URL pattern \"path('users/', UserViewSet.as_view(), name='user-list'),\\n    path('products/', ProductViewSet.as_view(), name='product-list'),\\n    path('orders/', OrderViewSet.as_view(), name='order-list'),\\n\" is invalid. Ensure that urlpatterns is a list of path() and/or re_path() instances.\n",
      "\tHINT: Try removing the string 'path('users/', UserViewSet.as_view(), name='user-list'),\n",
      "    path('products/', ProductViewSet.as_view(), name='product-list'),\n",
      "    path('orders/', OrderViewSet.as_view(), name='order-list'),\n",
      "'. The list of urlpatterns should not have a prefix string as the first element.\n",
      "\n",
      "System check identified 1 issue (0 silenced).\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 563, in check\n",
      "    raise SystemCheckError(msg)\n",
      "django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:\n",
      "\n",
      "ERRORS:\n",
      "?: (urls.E004) Your URL pattern \"path('users/', UserViewSet.as_view(), name='user-list'),\\n    path('products/', ProductViewSet.as_view(), name='product-list'),\\n    path('orders/', OrderViewSet.as_view(), name='order-list'),\\n\" is invalid. Ensure that urlpatterns is a list of path() and/or re_path() instances.\n",
      "\tHINT: Try removing the string 'path('users/', UserViewSet.as_view(), name='user-list'),\n",
      "    path('products/', ProductViewSet.as_view(), name='product-list'),\n",
      "    path('orders/', OrderViewSet.as_view(), name='order-list'),\n",
      "'. The list of urlpatterns should not have a prefix string as the first element.\n",
      "\n",
      "System check identified 1 issue (0 silenced).\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 563, in check\n",
      "    raise SystemCheckError(msg)\n",
      "django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:\n",
      "\n",
      "ERRORS:\n",
      "?: (urls.E004) Your URL pattern \"path('users/', UserViewSet.as_view(), name='user-list'),\\n    path('products/', ProductViewSet.as_view(), name='product-list'),\\n    path('orders/', OrderViewSet.as_view(), name='order-list'),\\n\" is invalid. Ensure that urlpatterns is a list of path() and/or re_path() instances.\n",
      "\tHINT: Try removing the string 'path('users/', UserViewSet.as_view(), name='user-list'),\n",
      "    path('products/', ProductViewSet.as_view(), name='product-list'),\n",
      "    path('orders/', OrderViewSet.as_view(), name='order-list'),\n",
      "'. The list of urlpatterns should not have a prefix string as the first element.\n",
      "\n",
      "System check identified 1 issue (0 silenced).\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 563, in check\n",
      "    raise SystemCheckError(msg)\n",
      "django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:\n",
      "\n",
      "ERRORS:\n",
      "?: (urls.E004) Your URL pattern \"path('users/', UserViewSet.as_view(), name='user-list'),\\n    path('products/', ProductViewSet.as_view(), name='product-list'),\\n    path('orders/', OrderViewSet.as_view(), name='order-list'),\\n\" is invalid. Ensure that urlpatterns is a list of path() and/or re_path() instances.\n",
      "\tHINT: Try removing the string 'path('users/', UserViewSet.as_view(), name='user-list'),\n",
      "    path('products/', ProductViewSet.as_view(), name='product-list'),\n",
      "    path('orders/', OrderViewSet.as_view(), name='order-list'),\n",
      "'. The list of urlpatterns should not have a prefix string as the first element.\n",
      "\n",
      "System check identified 1 issue (0 silenced).\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 563, in check\n",
      "    raise SystemCheckError(msg)\n",
      "django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:\n",
      "\n",
      "ERRORS:\n",
      "?: (urls.E004) Your URL pattern \"path('users/', UserViewSet.as_view(), name='user-list'),\\n    path('products/', ProductViewSet.as_view(), name='product-list'),\\n    path('orders/', OrderViewSet.as_view(), name='order-list'),\\n\" is invalid. Ensure that urlpatterns is a list of path() and/or re_path() instances.\n",
      "\tHINT: Try removing the string 'path('users/', UserViewSet.as_view(), name='user-list'),\n",
      "    path('products/', ProductViewSet.as_view(), name='product-list'),\n",
      "    path('orders/', OrderViewSet.as_view(), name='order-list'),\n",
      "'. The list of urlpatterns should not have a prefix string as the first element.\n",
      "\n",
      "System check identified 1 issue (0 silenced).\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 19, in <module>\n",
      "    path('users/', UserViewSet.as_view(), name='user-list'),\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\rest_framework\\viewsets.py\", line 83, in as_view\n",
      "    raise TypeError(\"The `actions` argument must be provided when \"\n",
      "TypeError: The `actions` argument must be provided when calling `.as_view()` on a ViewSet. For example `.as_view({'get': 'list'})`\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\serializers.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\models.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\serializers.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "[27/Mar/2025 10:29:20] \"GET /api/orders/ HTTP/1.1\" 200 14424\n",
      "Bad Request: /api/users/\n",
      "[27/Mar/2025 10:29:26] \"POST /api/users/ HTTP/1.1\" 400 14138\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 126, in inner_run\n",
      "    autoreload.raise_last_exception()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 87, in raise_last_exception\n",
      "    raise _exception[1]\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\__init__.py\", line 394, in execute\n",
      "    autoreload.check_errors(django.setup)()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\__init__.py\", line 24, in setup\n",
      "    apps.populate(settings.INSTALLED_APPS)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\registry.py\", line 91, in populate\n",
      "    app_config = AppConfig.create(entry)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\config.py\", line 193, in create\n",
      "    import_module(entry)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1324, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'Users'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 126, in inner_run\n",
      "    autoreload.raise_last_exception()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 87, in raise_last_exception\n",
      "    raise _exception[1]\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\__init__.py\", line 394, in execute\n",
      "    autoreload.check_errors(django.setup)()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\__init__.py\", line 24, in setup\n",
      "    apps.populate(settings.INSTALLED_APPS)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\registry.py\", line 91, in populate\n",
      "    app_config = AppConfig.create(entry)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\config.py\", line 193, in create\n",
      "    import_module(entry)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1324, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'Users'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 126, in inner_run\n",
      "    autoreload.raise_last_exception()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 87, in raise_last_exception\n",
      "    raise _exception[1]\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\__init__.py\", line 394, in execute\n",
      "    autoreload.check_errors(django.setup)()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\__init__.py\", line 24, in setup\n",
      "    apps.populate(settings.INSTALLED_APPS)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\registry.py\", line 91, in populate\n",
      "    app_config = AppConfig.create(entry)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\config.py\", line 193, in create\n",
      "    import_module(entry)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1324, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'users'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 126, in inner_run\n",
      "    autoreload.raise_last_exception()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 87, in raise_last_exception\n",
      "    raise _exception[1]\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\__init__.py\", line 394, in execute\n",
      "    autoreload.check_errors(django.setup)()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\__init__.py\", line 24, in setup\n",
      "    apps.populate(settings.INSTALLED_APPS)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\registry.py\", line 91, in populate\n",
      "    app_config = AppConfig.create(entry)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\apps\\config.py\", line 193, in create\n",
      "    import_module(entry)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1324, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'users'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\serializers.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 5, in <module>\n",
      "    from permissions import IsSeller, IsBuyer\n",
      "ModuleNotFoundError: No module named 'permissions'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 5, in <module>\n",
      "    from permissions import IsSeller, IsBuyer\n",
      "ModuleNotFoundError: No module named 'permissions'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 5, in <module>\n",
      "    from permissions import IsSeller, IsBuyer\n",
      "ModuleNotFoundError: No module named 'permissions'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 5, in <module>\n",
      "    from permissions import IsSeller, IsBuyer\n",
      "ModuleNotFoundError: No module named 'permissions'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 13, in <module>\n",
      "    class ProductViewSet(viewsets.ModelViewSet):\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 17, in ProductViewSet\n",
      "    filter_backends = [DjangoFilterBackend, filters.SearchFilter]\n",
      "                                            ^^^^^^^\n",
      "NameError: name 'filters' is not defined. Did you mean: 'filter'?\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 136, in check_custom_error_handlers\n",
      "    handler = resolver.resolve_error_handler(status_code)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 732, in resolve_error_handler\n",
      "    callback = getattr(self.urlconf_module, \"handler%s\" % view_type, None)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 13, in <module>\n",
      "    class ProductViewSet(viewsets.ModelViewSet):\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 17, in ProductViewSet\n",
      "    filter_backends = [DjangoFilterBackend, filter.SearchFilter]\n",
      "                                            ^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: type object 'filter' has no attribute 'SearchFilter'\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "Exception in thread django-main-thread:\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1075, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\threading.py\", line 1012, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\autoreload.py\", line 64, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\commands\\runserver.py\", line 134, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\management\\base.py\", line 486, in check\n",
      "    all_issues = checks.run_checks(\n",
      "                 ^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\registry.py\", line 88, in run_checks\n",
      "    new_errors = check(app_configs=app_configs, databases=databases)\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 44, in check_url_namespaces_unique\n",
      "    all_namespaces = _load_all_namespaces(resolver)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\core\\checks\\urls.py\", line 63, in _load_all_namespaces\n",
      "    url_patterns = getattr(resolver, \"url_patterns\", [])\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 718, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "                       ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\utils\\functional.py\", line 47, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "                                         ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\resolvers.py\", line 711, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\urls.py\", line 24, in <module>\n",
      "    path('api/', include('api.urls')),  # Make sure to include API URLs here\n",
      "                 ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\\django\\urls\\conf.py\", line 39, in include\n",
      "    urlconf_module = import_module(urlconf_module)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\importlib\\__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 999, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\urls.py\", line 3, in <module>\n",
      "    from .views import UserViewSet, ProductViewSet, OrderViewSet\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 13, in <module>\n",
      "    class ProductViewSet(viewsets.ModelViewSet):\n",
      "  File \"c:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py\", line 17, in ProductViewSet\n",
      "    filter_backends = [DjangoFilterBackend, filters.SearchFilter]\n",
      "                                            ^^^^^^^\n",
      "NameError: name 'filters' is not defined. Did you mean: 'filter'?\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\api\\views.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n",
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\\Tinash\\settings.py changed, reloading.\n",
      "Watching for file changes with StatReloader\n"
     ]
    }
   ],
   "source": [
    "!python manage.py runserver"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Name: djangorestframework\n",
      "Version: 3.15.2\n",
      "Summary: Web APIs for Django, made easy.\n",
      "Home-page: https://www.django-rest-framework.org/\n",
      "Author: Tom Christie\n",
      "Author-email: tom@tomchristie.com\n",
      "License: BSD\n",
      "Location: C:\\Users\\chris\\anaconda3\\envs\\price\\Lib\\site-packages\n",
      "Requires: django\n",
      "Required-by: \n"
     ]
    }
   ],
   "source": [
    "!pip show djangorestframework\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!python manage.py "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install djangorestframework-simplejwt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting django-filter\n",
      "  Downloading django_filter-25.1-py3-none-any.whl.metadata (5.1 kB)\n",
      "Requirement already satisfied: Django>=4.2 in c:\\users\\chris\\anaconda3\\envs\\price\\lib\\site-packages (from django-filter) (5.1.6)\n",
      "Requirement already satisfied: asgiref<4,>=3.8.1 in c:\\users\\chris\\anaconda3\\envs\\price\\lib\\site-packages (from Django>=4.2->django-filter) (3.8.1)\n",
      "Requirement already satisfied: sqlparse>=0.3.1 in c:\\users\\chris\\anaconda3\\envs\\price\\lib\\site-packages (from Django>=4.2->django-filter) (0.5.3)\n",
      "Requirement already satisfied: tzdata in c:\\users\\chris\\anaconda3\\envs\\price\\lib\\site-packages (from Django>=4.2->django-filter) (2025.1)\n",
      "Downloading django_filter-25.1-py3-none-any.whl (94 kB)\n",
      "Installing collected packages: django-filter\n",
      "Successfully installed django-filter-25.1\n"
     ]
    }
   ],
   "source": [
    "!pip install django-filter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No changes detected in app 'api'\n",
      "Operations to perform:\n",
      "  Apply all migrations: admin, api, auth, contenttypes, sessions\n",
      "Running migrations:\n",
      "  No migrations to apply.\n"
     ]
    }
   ],
   "source": [
    "!python manage.py makemigrations api\n",
    "!python manage.py migrate\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!python manage.py runserver"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash\n"
     ]
    }
   ],
   "source": [
    "%cd C:\\Users\\chris\\alx\\new_alx\\Alx_capstone_project\\Tinash"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "price",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
